@startuml
skinparam style strictuml


package Views {
    package Pages{}
    package Components{}
}
package Controllers{}
package Models{}
package Utils{}


Controllers <.u. Views

Models <.u. Controllers

Utils <.u. Controllers
Utils <.u. Models
Utils <.u. Views

Pages <.u. Components

@enduml