@startuml
skinparam style strictuml


actor User

boundary ExamAdminView
boundary NewExamView
boundary ExamPublishedView

entity Questions
entity Answers

control CreateExamController

User -- ExamAdminView
User -- NewExamView
ExamAdminView -r- NewExamView
NewExamView -r- ExamPublishedView

NewExamView -- CreateExamController


CreateExamController -- Questions
CreateExamController -r- Answers


@enduml