@startuml UC requestCertificate analysisCommunicationDiagram
skinparam actorstyle hollow
<style>
note {
    LineColor transparent
    BackgroundColor transparent
}
</style>
skinparam ranksep 1
skinparam nodesep 1

actor "Student" as user 
boundary ":ExamsView" as start
boundary ":CertificatesView" as myCertificates
boundary ":CertificateView" as certificateView
entity ":Course"  as course
control ":RequestCertificateController" as requestCertificateController
entity ":Certificate" as certificate


user -> start
note on link
    :requestCertificate()
end note

start --[hidden]> myCertificates
user -> myCertificates
note on link
    1 :requestCertificate()
end note

myCertificates -down-> requestCertificateController
note on link
    2 :requestCertificate(course)
end note

requestCertificateController -left-> certificateView
note on link
    5 :show(certificate)
end note

requestCertificateController -> course
note on link
    3 :summary = getSummary()
end note

requestCertificateController -down-> certificate
note on link
    4 :certificate = generateCertificate(summary)
end note

'certificateView - certificate

@enduml