@startuml
hide empty description

state "Inicial" as state1
state "Creando Examen" as state2
state "Usuario Registrado" as state3
state "Sesión Iniciada" as state4
state "Presentando Examen" as state7
state "Obteniendo Certificado" as state8
state state9 <<join>>

[*] --> state1

state1 -r-> state2 : Crear Examen
state2 -r-> state2 : Crear Pregunta
state1 --> state3 : Registrar Usuario

state3 --> state4 : Iniciar Sesión

state4 --> state4 : Consultar Ayuda
state4 --> state4 : Editar Perfil

state4 --> state7 : Presentar Examen
state7 --> state4 : Terminar Examen

state4 --> state8 : Solicitar Certificado

state4 --> state9
state8 --> state9

state9 --> [*] : Cerrar Sesión

@enduml