@startuml 

skinparam style strictuml
hide methods 

class "Administrador" as Admin

class "Certificado" as Certify {
    Nombre
    Apellido
    Profesor
    Tipo_Examen_Practicado
}

class "Usuario" as User {
    Correo
    Contraseña
    Preguntas_respondidas
}

class "Examen" as Exam {
    Tipo
    Duracion
    Instrucciones
}

class "Pregunta" as Question{
    Contenido
}

class "Respuesta" as Answer

class "Correcta" as Correct

class "Resumen" as Summary{
    Preguntas_Aprobadas
    Preguntas_Reprobadas
}

class "Dominio" as Domain

class "Curso" as Course

class "Explicacion" as Explanation

class "Linea" as Line

class "Texto" as Text

class "Codigo" as Code

class "Ayuda" as Help

class "Resultado" as Result

Question o-- Explanation

Admin --> "0..*" Exam : Crea

Admin --> "0..*" User : Registra

Question *-r- "4..*" Answer 

User -r- "0..*" Exam : Presenta

Exam *-r- "*" Question

Summary -d-o Certify 

Certify "0..*" <-down- User : Obtiene

Line "*" --* Answer

Line "*" --* Question

Summary ..> "*" Exam : Resume

User "0..*" --> Help : Consulta

User --> "0..*" Result : Lee

Exam --> Result : Genera

Text -d-|> Line

Code -d-|>Line

Question -d-o "*" Domain

Exam "*"-u-o Course

Certify -u-o Course

Correct -u-|> Answer

@enduml