@startuml Clases de analisis
hide footbox
actor Student
boundary ":MyExamsView" as MyExamsView
boundary ":ExamView" as ExamView
boundary ":ExamEndedView" as ExamEndedView
boundary ":AnswersView" as AnswersView
Control ":PresentExamController" as PresentExamController
entity ":Result" as Result
entity ":Answers" as Answers
entity ":Questions" as Questions

Student -> MyExamsView
Student -> ExamView

MyExamsView - ExamView
PresentExamController -down- Questions
PresentExamController -down- Answers
ExamView - PresentExamController
ExamView -right- PresentExamController
PresentExamController -right- Result
PresentExamController -right- ExamEndedView
PresentExamController -up- AnswersView



@enduml
