@startuml UC requestCertificate analysisClassDiagram
skinparam actorstyle hollow 

actor "Student" as user 
boundary "MyExamsView" as start
boundary "MyCertificatesView" as myCertificates
boundary "CertificateView" as certificateView
entity "Course"  as course
control "RequestCertificateController" as requestCertificateController
entity "Certificate" as certificate


user - start
user - myCertificates
start -- myCertificates
myCertificates -down- requestCertificateController
requestCertificateController -left- certificateView
requestCertificateController - course
requestCertificateController -down- certificate
'certificateView - certificate

@enduml