@startuml Design-Analysis-TraceDiagram
allow_mixing

    'analysis class
boundary AdminExamView 
boundary NewExamView 
boundary ExamPublishedView
control CreateExamController
entity Exam
entity Questions
entity Answers

    'design class
class AdminExamViewDes as "AdminExamView" <<JFrame>>
class NewExamViewDes as "NewExamView" <<JFrame>>
class ExamPublishedViewDes as "ExamPublishedView" <<JFrame>>
class CreateExamControllerDes as "CreateExamController"
class ExamDes as "Exam"
class QuestionsDes as "Questions"
class AnswersDes as "Answers"

AdminExamView <.. AdminExamViewDes: <trace>
NewExamView <.. NewExamViewDes: <trace>
ExamPublishedView <.. ExamPublishedViewDes: <trace>
CreateExamController <.. CreateExamControllerDes: <trace>
Exam <.. ExamDes: <trace>
Questions <.. QuestionsDes: <trace>
Answers <.. AnswersDes: <trace>

@enduml